### ISSUE TITLE
[Bug] transparent mode not working

### ISSUE THREAD

**Issue by Sturka209** [SpaceTheme/Steam#12]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [x] I have checked if I use the latest version

### Describe the Bug!

Trasparent mode not working for some reason

### Expected Behavior

it should make steam be trasnparent ig, idrk coz there weren't any pics about it

### Steps To Reproduce

go on settings, themes, spacetheme settings, transparent mode drop down menu choose one of the options

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
The bug is known, the transparent mode will probably be taken out again for the time being because it is a bit of work to do the whole thing

but it will come back when i have a better solution for it

**Comment by SpaceEnergy** [comment]
sorry for the late reply, but i decided to take the experiment out again as there will probably be a plugin for it in the future
