### ISSUE TITLE
[Bug] Styling beaks after entering Big Picture Mode

### ISSUE THREAD

**Issue by Thubbe42** [SpaceTheme/Steam#13]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

Steam big picture has incorrect styling when you enter then exit big picture mode.
![image](https://github.com/user-attachments/assets/a9c65a0e-e0c6-437c-9ae9-9e842b09886e)

### Expected Behavior

Default custom styling I guess.
![image](https://github.com/user-attachments/assets/6f8b57de-b1f1-4d4d-baaa-6fc870097ab9)

### Steps To Reproduce

1. Enter Big Picture Mode
2. Exit Big Picture Mode

### Operating System

Windows

**Comment by Thubbe42** [comment]
Damn, Just noticed it actually breaks far more than the big picture button.

It also breaks library and gamebar styling.
![image](https://github.com/user-attachments/assets/734f53bc-7ad2-4b2f-b45b-ebfdbf7032f0)

**Comment by SpaceEnergy** [comment]
This has nothing to do with the theme this is a bug of Millennium best you make a bug report there https://github.com/SteamClientHomebrew/Millennium/issues/new/choose

**Comment by Thubbe42** [comment]
> This has nothing to do with the theme this is a bug of Millennium best you make a bug report there https://github.com/SteamClientHomebrew/Millennium/issues/new/choose

Just noticed that might be the case. Thanks for beating me to it.
