### ISSUE TITLE
[Feature] Option to hide more steam bloat

### ISSUE THREAD

**Issue by Thubbe42** [SpaceTheme/Steam#14]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

Just option to hide steam bloat, akin to the "Add new shelf" button.

Specifically I'd like options to hide stuff such as "Enter Big Picture Mode", "News", and "Notification buttons. Bonus points for having collapsing buttons on the window control buttons.

**Comment by SpaceEnergy** [comment]
I have to talk to the dev of Millennium so that he can add something to the themes options so that the options are not so full but a little more minimal but basically I can do it with pleasure

**Comment by Thubbe42** [comment]
Hiding custom colors under a different tab would be nice. I guess it would be nice if millenium made it so theme dev could make custom tabs.

**Comment by SpaceEnergy** [comment]
would be really cool to clean up the options

**Comment by SpaceEnergy** [comment]
I once made 2 feature requests for both at millennium:
https://github.com/SteamClientHomebrew/Millennium/issues/92
https://github.com/SteamClientHomebrew/Millennium/issues/93

**Comment by Thubbe42** [comment]
Nice

**Comment by SpaceEnergy** [comment]
now that a few options have been added i'll close the issue but don't worry there will be more options to come
