### ISSUE TITLE
[Feature] Request navigate button

### ISSUE THREAD

**Issue by Junn1o** [SpaceTheme/Steam#16]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

Can you make the navigate button to the theme? Like the default
![image](https://github.com/user-attachments/assets/8cffa9bc-36bb-4102-a41c-11d0d13aefad)

**Comment by madmaxgrey** [comment]
they are centered to be designed wise, its how spacetheme has been since it was first made

**Comment by SpaceEnergy** [comment]
i will see if i can add an option to display the arrows again

**Comment by Junn1o** [comment]
> i will see if i can add an option to display the arrows again

Thanks! That will be great experience if you can do it.

**Comment by SpaceEnergy** [comment]
The whole thing was added with v1.1.0.1-alpha, but is off by default, to see the arrows you have to activate the option in the theme settings.

**Comment by Junn1o** [comment]
> The whole thing was added with v1.1.0.1-alpha, but is off by default, to see the arrows you have to activate the option in the theme settings

Thank you!
