### ISSUE TITLE
[Bug] Navigation buttons option wont enable

### ISSUE THREAD

**Issue by aidanbenny** [SpaceTheme/Steam#20]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

As the title suggests I tried enabling the navigation buttons in the themes options and after it prompts me to restart steam to apply the option it stays disabled.

Theme version: 1.1.0.1-alpha
Operating system: Windows 11

### Expected Behavior

The navigation buttons to appear after restarting steam

### Steps To Reproduce

1. open settings 2. go to themes 3. click the cog icon next to the selected theme 4. click on Steam bloat 5. enable the option for Navigate button 6. close the settings window 7. click restart on the prompt 

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
I think this is a bug from Millennium
workaround:
enable option and disable and then restart steam
or disable option an enable it

**Comment by SpaceEnergy** [comment]
info the option is on by default to see the arrows you have to turn it off
