### ISSUE TITLE
[Feature] Back & Forward bottuns

### ISSUE THREAD

**Issue by 1oym1** [SpaceTheme/Steam#21]
### Before Requesting

- [ ] I found no existing issue matching my feature request

### Describe the feature!

I noticed that the back and forward buttons are missing. Please add it.

**Comment by madmaxgrey** [comment]
goto the themes tab and click the settings icon it should give you more options pretty space added that there for people

**Comment by SpaceEnergy** [comment]
Yes, this can already be switched on in the settings

**Comment by 1oym1** [comment]
Never thought I would get the response this fast!!

Thank you so much and keep up the good work!
