### ISSUE TITLE
[Bug] Cant open "settings" in Themes

### ISSUE THREAD

**Issue by MrTALEX117** [SpaceTheme/Steam#22]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

In the themes window when i click the gear button a error appear

Something went wrong while displaying this content. Refresh
Error Reference: Shared SteamUI_9234223_8022c896960e5c48
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

![Screenshot 2024-10-07 195841](https://github.com/user-attachments/assets/16145d82-c9df-476d-ba72-66c86868176a)

Version v1.1.0.1 (alpha)
Win11

### Expected Behavior

I expected to see a settings for the theme whe i click a gear button

### Steps To Reproduce

1. Open settings.
2. Themes.
3. Click gear button.
4. See setting Theme instead a error

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
Not a SpaceTheme Bug.

Leave Steam Beta

**Comment by xVotexX** [comment]
> Not a SpaceTheme Bug.
> 
> Leave Steam Beta

When I try to access the settings menu, I get a similar error.
Steam Beta makes no difference for me. I tried both on and off and nothing worked.

**Error:**
```
Error Reference: Shared SteamUI_9319702_8022c896960e5c48
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

<img src="https://github.com/user-attachments/assets/b91c549a-4072-4d9a-b0e2-95b0e1d77a04" width="578">

![grafik](https://github.com/user-attachments/assets/610960b4-dedb-49a9-bc83-4047ba21e957)

**Comment by SpaceEnergy** [comment]
Is due to Millennium because of the new Steam update, will be fixed with the next Millennium update
