### ISSUE TITLE
[Bug] Missing minimize, resize and close icon in friend list chat

### ISSUE THREAD

**Issue by MrTALEX117** [SpaceTheme/Steam#23]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

In the chat window attached to the friends list, the minimize resize and close buttons are missing

![Screenshot 2024-10-07 193349](https://github.com/user-attachments/assets/02574c78-53b0-4d1b-8de3-4f3ab82bd471)

Version v1.1.0.1 (alpha)
Win11

### Expected Behavior

I expected to close the friends/chat window without using the Windows taskbar

### Steps To Reproduce

1. Open friends/chat.
2. Close or minimize the friends/chat window by clicking X or -

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
Already in progress #19
