### ISSUE TITLE
[Bug] Error in theme settings

### ISSUE THREAD

**Issue by MrTALEX117** [SpaceTheme/Steam#24]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

When i click on gear button in Steam Settings - Themes a error appear

> Something went wrong while displaying this content. Refresh
Error Reference: Shared SteamUI_9234223_8022c896960e5c48
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

![Screenshot 2024-10-07 195841](https://github.com/user-attachments/assets/e2e4f137-9fd3-45c5-abd0-37d0f813abd8)

Version v1.1.0.1 (alpha)
Win11

### Expected Behavior

See the theme setting when i click gear button

### Steps To Reproduce

1. Open Steam Settings
2. Themes
3. Click on gear button
4. The theme settings are shown

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
#22

**Comment by SpaceEnergy** [comment]
Please do not open issues unnecessarily if they have already been answered
