### ISSUE TITLE
[Bug] Game "Properties" window has an unclickable section

### ISSUE THREAD

**Issue by tdr1995** [SpaceTheme/Steam#27]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

When you open "Properties" of any game, "General" is in what I assume the title bar and can't be clicked (after clicking away).

![Screenshot 2024-10-14 073953](https://github.com/user-attachments/assets/1786f035-d537-4586-a9ed-d53aa3bc44a3)

### Expected Behavior

Be able to click back to General settings after moving to another section.

### Steps To Reproduce

1. Right click a game
2. Open "Properties..."
3. Click another option (i.e Installed Files)
4. Attempt to go back to General

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
will be fixed in v1.1.2-a
