### ISSUE TITLE
[Bug] Steam Wallpaper not fully shown

### ISSUE THREAD

**Issue by KirboCat** [SpaceTheme/Steam#28]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

![Screenshot 2024-10-19 225933](https://github.com/user-attachments/assets/f74b1ff0-92cc-47e2-98c2-164c80c36922)
![Screenshot 2024-10-19 225952](https://github.com/user-attachments/assets/1b755f56-4ea3-44ee-8621-769babf0314f)
When I use SpaceTheme Steam Wallpapers aren't fully shown anymore and only the middle Part is shown with black borders on the sides.

**Comment by madmaxgrey** [comment]
the webkit is still in the works for spacetheme

**Comment by SpaceEnergy** [comment]
fixed in v1.1.3-a
