### ISSUE TITLE
[Feature] Forward & Back Buttons

### ISSUE THREAD

**Issue by An3kii** [SpaceTheme/Steam#29]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

The Space Theme seems to be missing the Forward and Back buttons. Is this intentional? Can they be added? Thanks!

**Comment by SpaceEnergy** [comment]
![{AA367B66-1FEC-4948-87DA-02BC9B86D05F}](https://github.com/user-attachments/assets/b9a5cb38-880c-47ee-956f-47e019c6718b)

**Comment by An3kii** [comment]
I tried this - it doesn't seem to be working. I had to manually change the value of navigateButton.css

**Comment by SpaceEnergy** [comment]
@An3kii so the option works, but currently Millennium has a bug where the options are not saved correctly (or the current status of the option is not recognized correctly) so you have to turn the option off, on, off, on, off (you can also just do off, on, off) (off stands for showing the buttons) and then close the settings window and then click on the button with restart and then you can see them
