### ISSUE TITLE
[Bug] Error Reference: Shared SteamUI_9319702_8022c896960e5c48

### ISSUE THREAD

**Issue by DeveloperrEva** [SpaceTheme/Steam#31]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

Something went wrong while displaying this content. Refresh

Error Reference: Shared SteamUI_9319702_8022c896960e5c48
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings

![изображение](https://github.com/user-attachments/assets/7191cdc3-ef39-4d18-948f-a19996df3249)

### Expected Behavior

So that this doesn't happen

### Steps To Reproduce

1. Open Settings

### Operating System

Windows

**Comment by SpaceEnergy** [comment]
not a theme bug is due to Millennium because of the new Steam update, will be fixed with the next Millennium update
