### ISSUE TITLE
[Bug] React Error (Linux)

### ISSUE THREAD

**Issue by RaymondRunner** [SpaceTheme/Steam#39]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I found no existing issues matching my bug on the [Millennium Repo](https://github.com/shdwmtr/millennium/issues)
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

Every time i try to enter the theme settings it just throws an error of ReactJS. "Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

I'm using millennium on arch linux and the app works pretty well, but the theme not so much...
PD: Steam did not update recently, i saw that there was another entry of the same error.

![Captura de pantalla de 2024-12-02 05-25-19](https://github.com/user-attachments/assets/ad7eacae-2145-4c6e-83bf-56b9dd8d666e)

### Expected Behavior

I expected the pop up that let me change colors from the theme.

### Steps To Reproduce

1. Open Steam With Millenium
2. Set The Skin
3. Open The Skin Settings.

### Operating System

Linux

**Comment by SpaceEnergy** [comment]
Millennium Bug, please report it here: https://github.com/shdwmtr/millennium/issues/new/choose
