### ISSUE TITLE
[Bug] Hide VAC Ban option not working correctly

### ISSUE THREAD

**Issue by Czekoloczek** [SpaceTheme/Steam#40]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] I found no existing issues matching my bug on the [Millennium Repo](https://github.com/shdwmtr/millennium/issues)
- [X] I completely restarted Steam and checked if the bug is still there
- [X] I have checked if I use the latest version

### Describe the Bug!

![obraz](https://github.com/user-attachments/assets/7cc454bc-6253-4bca-aee7-60c462f2de72)
SpaceTheme hides my game-ban, despite the option for VAC-ban visibility being selected as "show".
(This might be an issue with https://github.com/shdwmtr/millennium/issues/148, but i spammed the show option, restarted steam and it still didn't work.)

### Expected Behavior

I can see my game-ban

### Steps To Reproduce

- Select "show" option in VAC-ban visibility
- Open a profile with a game or VAC ban (ex. https://steamcommunity.com/id/Czekoloczek/)

### Operating System

Windows

**Comment by Czekoloczek** [comment]
If this is an issue with https://github.com/shdwmtr/millennium/issues/148, then you can close this issue

**Comment by SpaceEnergy** [comment]
Yes, it has something to do with https://github.com/shdwmtr/millennium/issues/148 because if you look here https://github.com/SpaceTheme/Steam/blob/main/skin.json#L143-L151 the theme itself does not patch CSS when the option is set to Show.
