### ISSUE TITLE
[Bug] the chat window has no window controls

### ISSUE THREAD

**Issue by pcc404** [SpaceTheme/Steam#8]
![Screenshot 2024-07-01 182701](https://github.com/SpaceEnergy/SpaceTheme-Steam/assets/58848854/e5b22c9e-f54b-4544-8b1b-9618ba12716f)
  

i'll try to fix it myself for now

**Comment by SpaceEnergy** [comment]
will be fixed with v1.1.0-alpha until then you have to close the window via the windows taskbar
